"""
Complete Character Skill Trees for All 21 Students
Copy this into mha_roguelike_complete.py to replace get_character_skill_tree function
"""

def get_character_skill_tree(character_name):
    """Returns character-specific skill tree - ALL 21 CHARACTERS"""
    skill_trees = {
        "Izuku Midoriya": {
            'full_cowling_mastery': {'level': 0, 'max': 3, 'type': 'combat', 
                                     'desc': 'Increases attack by 6 per level', 
                                     'bonus': {'attack': 6}},
            'shoot_style': {'level': 0, 'max': 2, 'type': 'combat', 
                           'desc': 'Increases evasion by 8% per level', 
                           'bonus': {'evasion': 8}},
            'danger_sense': {'level': 0, 'max': 1, 'type': 'utility', 
                            'desc': '25% chance to avoid ambushes', 
                            'bonus': {'enemy_avoid': 25}},
        },
        "Katsuki Bakugo": {
            'explosive_power': {'level': 0, 'max': 3, 'type': 'combat', 
                               'desc': 'Increases attack by 8 per level', 
                               'bonus': {'attack': 8}},
            'armor_piercing': {'level': 0, 'max': 2, 'type': 'combat', 
                              'desc': 'Increases attack by 5 per level', 
                              'bonus': {'attack': 5}},
            'blast_rush': {'level': 0, 'max': 1, 'type': 'utility',
                          'desc': '20% chance to ambush enemies',
                          'bonus': {'ambush': 20}},
        },
        "Shoto Todoroki": {
            'temperature_control': {'level': 0, 'max': 3, 'type': 'combat', 
                                   'desc': 'Increases attack and defense by 4', 
                                   'bonus': {'attack': 4, 'defense': 4}},
            'heaven_piercing_ice_wall': {'level': 0, 'max': 2, 'type': 'combat', 
                                        'desc': 'Increases defense by 6 per level', 
                                        'bonus': {'defense': 6}},
            'dual_element_master': {'level': 0, 'max': 1, 'type': 'combat',
                                   'desc': 'Increases HP by 25',
                                   'bonus': {'hp': 25}},
        },
        "Ochaco Uraraka": {
            'zero_gravity_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                    'desc': 'Increases evasion by 10% per level',
                                    'bonus': {'evasion': 10}},
            'meteor_shower': {'level': 0, 'max': 2, 'type': 'combat',
                             'desc': 'Increases attack by 5 per level',
                             'bonus': {'attack': 5}},
            'weightless_combat': {'level': 0, 'max': 1, 'type': 'utility',
                                 'desc': 'Reduces energy costs by 15%',
                                 'bonus': {'energy': 10}},
        },
        "Tenya Iida": {
            'engine_boost': {'level': 0, 'max': 3, 'type': 'combat',
                            'desc': 'Increases attack by 6 per level',
                            'bonus': {'attack': 6}},
            'recipro_turbo': {'level': 0, 'max': 2, 'type': 'combat',
                             'desc': 'Increases evasion by 8% per level',
                             'bonus': {'evasion': 8}},
            'emergency_exit': {'level': 0, 'max': 1, 'type': 'utility',
                              'desc': '25% chance to avoid enemy encounters',
                              'bonus': {'enemy_avoid': 25}},
        },
        "Tsuyu Asui": {
            'camofrog': {'level': 0, 'max': 3, 'type': 'combat', 
                        'desc': 'Increases evasion by 12% and ambush by 8%', 
                        'bonus': {'evasion': 12, 'ambush': 8}},
            'powerful_leap': {'level': 0, 'max': 2, 'type': 'combat', 
                             'desc': 'Increases attack by 5 per level', 
                             'bonus': {'attack': 5}},
            'tongue_grab': {'level': 0, 'max': 1, 'type': 'utility', 
                           'desc': '30% better items and secrets', 
                           'bonus': {'item_find': 30, 'secret_detection': 20}},
        },
        "Eijiro Kirishima": {
            'unbreakable': {'level': 0, 'max': 3, 'type': 'combat',
                           'desc': 'Increases defense by 8 per level',
                           'bonus': {'defense': 8}},
            'red_riot': {'level': 0, 'max': 2, 'type': 'combat',
                        'desc': 'Increases HP by 20 per level',
                        'bonus': {'hp': 20}},
            'manly_spirit': {'level': 0, 'max': 1, 'type': 'utility',
                            'desc': 'Increases attack by 10',
                            'bonus': {'attack': 10}},
        },
        "Momo Yaoyorozu": {
            'creation_mastery': {'level': 0, 'max': 3, 'type': 'utility',
                                'desc': '15% better item find per level',
                                'bonus': {'item_find': 15}},
            'tactical_genius': {'level': 0, 'max': 2, 'type': 'combat',
                               'desc': 'Increases energy by 10 per level',
                               'bonus': {'energy': 10}},
            'emergency_creation': {'level': 0, 'max': 1, 'type': 'utility',
                                  'desc': '20% chance to find secrets',
                                  'bonus': {'secret_detection': 20}},
        },
        "Denki Kaminari": {
            'voltage_control': {'level': 0, 'max': 3, 'type': 'combat',
                               'desc': 'Increases attack by 6 per level',
                               'bonus': {'attack': 6}},
            'indiscriminate_shock': {'level': 0, 'max': 2, 'type': 'combat',
                                    'desc': 'Increases energy by 8 per level',
                                    'bonus': {'energy': 8}},
            'charging_station': {'level': 0, 'max': 1, 'type': 'utility',
                                'desc': 'Restore 5 energy per room entered',
                                'bonus': {'energy': 5}},
        },
        "Fumikage Tokoyami": {
            'dark_shadow_control': {'level': 0, 'max': 3, 'type': 'combat',
                                   'desc': 'Increases attack by 7 per level',
                                   'bonus': {'attack': 7}},
            'black_ankh': {'level': 0, 'max': 2, 'type': 'combat',
                          'desc': 'Increases defense by 5 per level',
                          'bonus': {'defense': 5}},
            'shadow_ambush': {'level': 0, 'max': 1, 'type': 'utility',
                             'desc': '25% chance to ambush enemies',
                             'bonus': {'ambush': 25}},
        },
        "Shoji Mezo": {
            'dupli_arms_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                  'desc': 'Increases attack by 5 per level',
                                  'bonus': {'attack': 5}},
            'organ_enhancement': {'level': 0, 'max': 2, 'type': 'combat',
                                 'desc': 'Increases HP by 20 per level',
                                 'bonus': {'hp': 20}},
            'sensory_overload': {'level': 0, 'max': 1, 'type': 'utility',
                                'desc': '30% better secret detection',
                                'bonus': {'secret_detection': 30}},
        },
        "Mina Ashido": {
            'acid_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                            'desc': 'Increases attack by 6 per level',
                            'bonus': {'attack': 6}},
            'acid_armor': {'level': 0, 'max': 2, 'type': 'combat',
                          'desc': 'Increases defense by 5 per level',
                          'bonus': {'defense': 5}},
            'acid_slide': {'level': 0, 'max': 1, 'type': 'utility',
                          'desc': 'Increases evasion by 15%',
                          'bonus': {'evasion': 15}},
        },
        "Kyoka Jiro": {
            'heartbeat_fuzz_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                      'desc': 'Increases attack by 6 per level',
                                      'bonus': {'attack': 6}},
            'sound_detection': {'level': 0, 'max': 2, 'type': 'utility',
                               'desc': '15% better secret detection per level',
                               'bonus': {'secret_detection': 15}},
            'sonic_evasion': {'level': 0, 'max': 1, 'type': 'combat',
                             'desc': 'Increases evasion by 12%',
                             'bonus': {'evasion': 12}},
        },
        "Hanta Sero": {
            'tape_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                            'desc': 'Increases attack by 5 per level',
                            'bonus': {'attack': 5}},
            'swing_mobility': {'level': 0, 'max': 2, 'type': 'combat',
                              'desc': 'Increases evasion by 10% per level',
                              'bonus': {'evasion': 10}},
            'tape_conservation': {'level': 0, 'max': 1, 'type': 'utility',
                                 'desc': 'Increases energy by 15',
                                 'bonus': {'energy': 15}},
        },
        "Mashirao Ojiro": {
            'tail_strike_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                   'desc': 'Increases attack by 6 per level',
                                   'bonus': {'attack': 6}},
            'martial_arts_training': {'level': 0, 'max': 2, 'type': 'combat',
                                     'desc': 'Increases HP by 15 per level',
                                     'bonus': {'hp': 15}},
            'tail_balance': {'level': 0, 'max': 1, 'type': 'combat',
                            'desc': 'Increases defense by 8',
                            'bonus': {'defense': 8}},
        },
        "Toru Hagakure": {
            'invisibility_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                    'desc': 'Increases evasion by 15% per level',
                                    'bonus': {'evasion': 15}},
            'light_refraction': {'level': 0, 'max': 2, 'type': 'combat',
                                'desc': 'Increases attack by 5 per level',
                                'bonus': {'attack': 5}},
            'stealth_master': {'level': 0, 'max': 1, 'type': 'utility',
                              'desc': '30% chance to ambush enemies',
                              'bonus': {'ambush': 30}},
        },
        "Koji Koda": {
            'anivoice_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                'desc': 'Increases attack by 5 per level',
                                'bonus': {'attack': 5}},
            'animal_friendship': {'level': 0, 'max': 2, 'type': 'utility',
                                 'desc': '20% better item find per level',
                                 'bonus': {'item_find': 20}},
            'gentle_giant': {'level': 0, 'max': 1, 'type': 'combat',
                            'desc': 'Increases HP by 25',
                            'bonus': {'hp': 25}},
        },
        "Rikido Sato": {
            'sugar_rush_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                  'desc': 'Increases attack by 8 per level',
                                  'bonus': {'attack': 8}},
            'sweet_power': {'level': 0, 'max': 2, 'type': 'combat',
                           'desc': 'Increases HP by 20 per level',
                           'bonus': {'hp': 20}},
            'sugar_reserves': {'level': 0, 'max': 1, 'type': 'utility',
                              'desc': 'Increases energy by 12',
                              'bonus': {'energy': 12}},
        },
        "Yuga Aoyama": {
            'navel_laser_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                   'desc': 'Increases attack by 7 per level',
                                   'bonus': {'attack': 7}},
            'belly_fortification': {'level': 0, 'max': 2, 'type': 'combat',
                                   'desc': 'Increases energy by 10 per level',
                                   'bonus': {'energy': 10}},
            'sparkling_evasion': {'level': 0, 'max': 1, 'type': 'combat',
                                 'desc': 'Increases evasion by 10%',
                                 'bonus': {'evasion': 10}},
        },
        "Minoru Mineta": {
            'pop_off_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                               'desc': 'Increases attack by 5 per level',
                               'bonus': {'attack': 5}},
            'sticky_defense': {'level': 0, 'max': 2, 'type': 'combat',
                              'desc': 'Increases defense by 6 per level',
                              'bonus': {'defense': 6}},
            'grape_escape': {'level': 0, 'max': 1, 'type': 'utility',
                            'desc': '20% chance to avoid enemies',
                            'bonus': {'enemy_avoid': 20}},
        },
        "Hitoshi Shinso": {
            'brainwashing_mastery': {'level': 0, 'max': 3, 'type': 'combat',
                                    'desc': 'Increases attack by 6 per level',
                                    'bonus': {'attack': 6}},
            'psychic_domination': {'level': 0, 'max': 2, 'type': 'combat',
                                  'desc': 'Increases energy by 10 per level',
                                  'bonus': {'energy': 10}},
            'mental_fortitude': {'level': 0, 'max': 1, 'type': 'combat',
                                'desc': 'Increases defense by 8',
                                'bonus': {'defense': 8}},
        },
    }
    return skill_trees.get(character_name, {})
